// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ??
        'AIzaSyBxm6J_UI-mfJOT-LqovLjKGHxVXlFEu78',
    appId: '1:185739276739:web:935f8239d614f4e05d8d76',
    messagingSenderId: '185739276739',
    projectId: 'my-pocket-fb67d',
    authDomain: 'my-pocket-fb67d.firebaseapp.com',
    storageBucket: 'my-pocket-fb67d.firebasestorage.app',
    measurementId: 'G-0CHKTPLHD4',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
    appId: '1:185739276739:android:118e8c47070f3d9b5d8d76',
    messagingSenderId: '185739276739',
    projectId: 'my-pocket-fb67d',
    storageBucket: 'my-pocket-fb67d.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
    appId: '1:185739276739:ios:917285c47ff52d4e5d8d76',
    messagingSenderId: '185739276739',
    projectId: 'my-pocket-fb67d',
    storageBucket: 'my-pocket-fb67d.firebasestorage.app',
    iosClientId:
        '185739276739-ekbvrhvunp1gfogo6c6osi9vetl8p2gq.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPocket',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_MACOS_API_KEY'] ?? '',
    appId: '1:185739276739:ios:917285c47ff52d4e5d8d76',
    messagingSenderId: '185739276739',
    projectId: 'my-pocket-fb67d',
    storageBucket: 'my-pocket-fb67d.firebasestorage.app',
    iosClientId:
        '185739276739-ekbvrhvunp1gfogo6c6osi9vetl8p2gq.apps.googleusercontent.com',
    iosBundleId: 'com.example.myPocket',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WINDOWS_API_KEY'] ?? '',
    appId: '1:185739276739:web:2a2f732c5317c8a85d8d76',
    messagingSenderId: '185739276739',
    projectId: 'my-pocket-fb67d',
    authDomain: 'my-pocket-fb67d.firebaseapp.com',
    storageBucket: 'my-pocket-fb67d.firebasestorage.app',
    measurementId: 'G-V13Y6FXSGN',
  );
}
